FROM node:16.14.2-alpine
WORKDIR /app
COPY . .
RUN npm install
Run npm install axios react-bootstrap bootstrap 
Run npm install react-router-dom sweetalert2 --save
RUN npm run build
ENTRYPOINT npm start